services:
  db:
    image: mongo
    container_name: imobi-mongo-db
    restart: always
    ports:
      - "${HOST_EXTERNAL_PORT_MONGO}:27017"
    environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env